### PR TITLE
Move GzipFieldTokenizer to Groovy code

### PR DESCRIPTION
**Pull request by JanKanis**
The groovy compiler has no problems with the current implementation, unlike an older version that used primitive arrays extensively. Groovify
the code in the process.

Also remove asCharArray and corresponding tests as it is no longer used.

### CODE REVIEW

**Comment by cataphract** [comment]
Have you benchmarked this? `as Foobar`, where `Foobar` is not a well-known class to Groovy is one of the most expensive operations in Groovy. And it seems it's being called at least once per SNP.

**Comment by JanKanis** [comment]
initial benchmark: converting a blob with 7000 snps to a list 2000 times, best of 20:
java version: 220 µs per one row
groovy version: 2078 µs per one row

So parsing 10000 rows with the groovy version would give an overhead of +/- 20 seconds, I'm not sure if that is acceptable. 

I had a look at the generated bytecode and groovy's output is a lot less optimized than I would have thought (even " ' ' as char " which is the official way of writing a char literal, creates a string and converts it to a char on every loop iteration :disappointed:). I'll see if I can improve it a bit.

**Comment by JanKanis** [comment]
Some more benchmarks: for the java version, asStringList takes 220 µs per row, but asDoubleArray 2365 µs. For the groovy version asDoubleArray is 2386 µs.

**Comment by JanKanis** [comment]
New implementation that almost performs as fast as the equivalent Java, and is better than the original Java code: 

Java:
  asStringList: 231.5 µs per row
  asDoubleArray: 541 µs per row

Groovy:
  asStringList: 249 µs per row
  asDoubleArray: 577 µs per row

Ready to be merged as far as I'm concerned.

**Pull request merged**
